import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import path from 'path';

const dbUrl = process.env.DATABASE_URL ?? `file:${path.resolve(process.cwd(), 'prisma/dev.db')}`;
process.env.DATABASE_URL = dbUrl;

const prisma = new PrismaClient();

const EXTRA_SKILLS = [
  {
    name: 'canvas-design',
    nameLang: 'en',
    summaryCn: '在画布上创建精美的视觉设计、社交媒体图片、海报和营销素材。支持品牌配色、图层组合和导出 PNG/SVG。',
    description: 'Create beautiful visual designs, social media images, posters, and marketing materials on a canvas.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/canvas-design/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-15',
  },
  {
    name: 'brand-guidelines',
    nameLang: 'en',
    summaryCn: '根据品牌指南（颜色、字体、语调、Logo 使用规范）创建一致的视觉内容。确保生成物符合品牌识别系统。',
    description: 'Create consistent visual content following brand guidelines (colors, fonts, tone, logo usage).',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/brand-guidelines/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-05',
  },
  {
    name: 'security-review',
    nameLang: 'en',
    summaryCn: '全面的代码安全审查：识别 SQL 注入、XSS、认证绕过、敏感信息泄露等漏洞，提供修复建议和优先级排序。',
    description: 'Comprehensive security code review: identify SQL injection, XSS, auth bypass, sensitive data leaks.',
    category: 'testing-security',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/security-review/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-18',
  },
  {
    name: 'performance-optimizer',
    nameLang: 'en',
    summaryCn: '分析前端性能瓶颈：Bundle 大小、渲染性能、内存泄漏、网络请求。提供优化方案和 measurable 改进建议。',
    description: 'Analyze frontend performance bottlenecks: bundle size, render performance, memory leaks, network requests.',
    category: 'development',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/performance/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-12',
  },
  {
    name: 'accessibility-audit',
    nameLang: 'en',
    summaryCn: 'Web 可访问性审计：检查 ARIA 标签、对比度、键盘导航、屏幕阅读器兼容性，确保符合 WCAG 2.1 AA 标准。',
    description: 'Web accessibility audit: ARIA labels, contrast, keyboard navigation, screen reader compatibility (WCAG 2.1 AA).',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/accessibility/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-01-20',
  },
  {
    name: 'email-writer',
    nameLang: 'en',
    summaryCn: '撰写专业邮件：商务沟通、客户跟进、内部通知、危机公关。支持不同语气（正式/友好/简洁）和结构化模板。',
    description: 'Write professional emails: business communication, client follow-up, internal notices, crisis PR.',
    category: 'business',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/email/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-22',
  },
  {
    name: 'meeting-notes',
    nameLang: 'en',
    summaryCn: '将会议录音/文字记录整理为结构化会议纪要：决策项、行动项（含负责人和 DDL）、开放问题、关键讨论。',
    description: 'Convert meeting transcripts into structured notes: decisions, action items (owner + deadline), open questions.',
    category: 'business',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/meeting-notes/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-08',
  },
  {
    name: 'competitive-analysis',
    nameLang: 'en',
    summaryCn: '生成竞品分析：功能对比矩阵、优劣势评估、市场定位、差异化策略。支持表格和可视化呈现。',
    description: 'Generate competitive analysis: feature comparison matrix, SWOT, market positioning, differentiation strategy.',
    category: 'business',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/competitive/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-28',
  },
  {
    name: 'financial-modeling',
    nameLang: 'en',
    summaryCn: '构建财务模型：收入预测、成本结构、现金流、单位经济分析。输出可调整的 Excel/Google Sheets 模型。',
    description: 'Build financial models: revenue forecast, cost structure, cash flow, unit economics.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/finance/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', '通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-15',
  },
  {
    name: 'data-visualization',
    nameLang: 'en',
    summaryCn: '将数据集转化为清晰的可视化图表：选择合适图表类型、配色方案、标注重点。支持 D3、ECharts、Matplotlib。',
    description: 'Transform datasets into clear visualizations: chart type selection, color schemes, annotations.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/dataviz/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-12',
  },
  {
    name: 'typecript-best-practices',
    nameLang: 'en',
    summaryCn: 'TypeScript 类型安全最佳实践：泛型、类型推断、严格模式配置、避免 any、实用工具类型。提升代码健壮性。',
    description: 'TypeScript type safety best practices: generics, type inference, strict mode, utility types.',
    category: 'development',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/ts-best-practices/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor']),
    author: 'vercel-labs',
    stars: 28800,
    sourceUpdatedAt: '2026-04-20',
  },
  {
    name: 'nextjs-app-router',
    nameLang: 'en',
    summaryCn: 'Next.js App Router 开发指南：Server Components、路由约定、数据获取、中间件、流式渲染。遵循官方推荐模式。',
    description: 'Next.js App Router guide: Server Components, routing conventions, data fetching, middleware, streaming.',
    category: 'development',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/nextjs-app-router/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor']),
    author: 'vercel-labs',
    stars: 28800,
    sourceUpdatedAt: '2026-04-18',
  },
  {
    name: 'python-refactor',
    nameLang: 'en',
    summaryCn: 'Python 代码重构助手：消除重复、改善命名、应用设计模式、提升可读性和性能。支持 PEP 8 规范。',
    description: 'Python refactoring assistant: remove duplication, improve naming, apply design patterns, PEP 8.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/py-refactor/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Codex', 'Cursor', '通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-05-10',
  },
  {
    name: 'docker-helper',
    nameLang: 'en',
    summaryCn: 'Docker 配置助手：编写高效 Dockerfile、多阶段构建、docker-compose 编排、镜像体积优化。',
    description: 'Docker config helper: efficient Dockerfiles, multi-stage builds, docker-compose, image size optimization.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/docker/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-05-22',
  },
  {
    name: 'kubernetes-ops',
    nameLang: 'en',
    summaryCn: 'Kubernetes 运维助手：编写 YAML 清单、排查 Pod 故障、配置 HPA/资源限制、滚动更新策略。',
    description: 'Kubernetes ops assistant: YAML manifests, pod troubleshooting, HPA, rolling updates.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/k8s/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-05-18',
  },
  {
    name: 'social-media-manager',
    nameLang: 'en',
    summaryCn: '社交媒体内容管理：生成多平台文案（Twitter/X、LinkedIn、小红书）、话题标签策略、发布排期。',
    description: 'Social media content manager: multi-platform copy, hashtag strategy, posting schedule.',
    category: 'content-media',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/social/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-02',
  },
  {
    name: 'technical-writer',
    nameLang: 'en',
    summaryCn: '技术文档写作：API 文档、教程、README、架构说明。结构化、准确、面向目标读者群体。',
    description: 'Technical writing: API docs, tutorials, README, architecture explanations.',
    category: 'content-media',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/tech-writer/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', '通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-26',
  },
  {
    name: 'video-script-generator',
    nameLang: 'en',
    summaryCn: '视频脚本生成：开场钩子、内容结构、转场提示、CTA。支持 YouTube、抖音、B 站等平台风格。',
    description: 'Video script generator: hook, structure, transitions, CTA. YouTube/Douyin/Bilibili styles.',
    category: 'content-media',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/video-script/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-18',
  },
  {
    name: 'rag-pipeline',
    nameLang: 'en',
    summaryCn: '构建 RAG 检索增强生成流水线：文档分块、向量化、相似度检索、上下文组装、幻觉缓解。',
    description: 'Build RAG pipeline: chunking, embedding, similarity search, context assembly, hallucination mitigation.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/rag/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-06-05',
  },
  {
    name: 'logo-generator',
    nameLang: 'en',
    summaryCn: '生成 SVG 矢量 Logo：简洁、可缩放、品牌化。输出可直接用于网页和印刷的矢量图。',
    description: 'Generate SVG vector logos: clean, scalable, on-brand. Output ready for web and print.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/logo/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-08',
  },
];

async function seed() {
  console.log('🌱 导入额外种子数据...');
  let imported = 0;
  let skipped = 0;

  for (const skill of EXTRA_SKILLS) {
    const existing = await prisma.skill.findFirst({ where: { sourceUrl: skill.sourceUrl } });
    if (existing) { skipped++; continue; }

    await prisma.skill.create({
      data: {
        ...skill,
        tags: '[]',
        isNew: 1,
        status: 'published',
        createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
      },
    });
    imported++;
  }

  console.log(`✅ 导入完成: 新增 ${imported} 个, 跳过 ${skipped} 个`);
  console.log(`📊 数据库共有 ${await prisma.skill.count()} 个 Skill`);
}

seed()
  .catch((e) => { console.error('❌ 失败:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
