/**
 * 种子数据导入脚本
 * 运行: npx tsx scripts/seed.ts
 */

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaLibSql } from '@prisma/adapter-libsql';

const adapter = new PrismaLibSql({
  url: process.env.DATABASE_URL ?? 'file:./prisma/dev.db',
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const prisma = new PrismaClient({ adapter });

const SEED_SKILLS = [
  {
    name: 'frontend-design',
    nameLang: 'en',
    summaryCn: '为构建新 UI 或重塑现有界面提供独特、有意图的视觉设计指导，涵盖美学方向、排版及避免模板化默认风格的选择。',
    description: 'Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don\'t read as templated defaults.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/frontend-design/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-06-09',
  },
  {
    name: 'skill-creator',
    nameLang: 'en',
    summaryCn: '创建新技能、修改和改进现有技能，并评估技能性能。用于从零创建技能、编辑或优化现有技能、运行评估测试、基准测试及优化触发准确率。',
    description: 'Create new skills, modify and improve existing skills, and measure skill performance.',
    category: 'development',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/skill-creator/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-04-20',
  },
  {
    name: 'ui-ux-pro-max',
    nameLang: 'en',
    summaryCn: 'Web 和移动端 UI/UX 设计智能助手。包含 50+ 风格、161 种调色板、57 种字体搭配、99 条 UX 指南和 25 种图表类型，覆盖 10 个技术栈。',
    description: 'UI/UX design intelligence for web and mobile. Includes 50+ styles, 161 color palettes, 57 font pairings, 99 UX guidelines.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor']),
    author: 'nextlevelbuilder',
    stars: 102000,
    sourceUpdatedAt: '2026-07-02',
  },
  {
    name: 'brainstorming',
    nameLang: 'en',
    summaryCn: '在任何创造性工作之前必须使用的技能——创建功能、构建组件、添加功能或修改行为时，探索用户意图、需求和设计思路。',
    description: 'You MUST use this before any creative work - creating features, building components, adding functionality, or modifying behavior.',
    category: 'development',
    sourceUrl: 'https://github.com/obra/superpowers/blob/main/skills/brainstorming/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'obra',
    stars: 248200,
    sourceUpdatedAt: '2026-06-30',
  },
  {
    name: 'browser-use',
    nameLang: 'en',
    summaryCn: '通过 CDP 直接控制浏览器进行 Web 交互：自动化操作、数据抓取、测试、截图及网站/应用操作。',
    description: 'Direct browser control via CDP for web interaction: automation, scraping, testing, screenshots, and site/app work.',
    category: 'testing-security',
    sourceUrl: 'https://github.com/browser-use/browser-use',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', '通用']),
    author: 'browser-use',
    stars: 103200,
    sourceUpdatedAt: '2026-07-01',
  },
  {
    name: 'code-reviewer',
    nameLang: 'en',
    summaryCn: '全面的代码审查，专注于安全性、性能和最佳实践。用于审查代码、执行安全审计、检查代码质量或排查安全漏洞和性能问题。',
    description: 'Thorough code review with focus on security, performance, and best practices.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/code-reviewer/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor', '通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-06-13',
  },
  {
    name: 'docx',
    nameLang: 'en',
    summaryCn: '创建、读取、编辑和操作 Word 文档（.docx 文件）。支持生成带目录、标题、页码的专业文档，也可从 .docx 提取内容、插入图片等。',
    description: 'Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files).',
    category: 'office-productivity',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/docx/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-25',
  },
  {
    name: 'ppt-generation',
    nameLang: 'en',
    summaryCn: '生成演示文稿（PPT/PPTX），通过为每张幻灯片生成图像并组合成 PowerPoint 文件来创建视觉丰富的幻灯片。',
    description: 'Use this skill when the user requests to generate, create, or make presentations (PPT/PPTX).',
    category: 'office-productivity',
    sourceUrl: 'https://github.com/bytedance/deer-flow/blob/main/skills/ppt-generation/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', '通用']),
    author: 'bytedance',
    stars: 76300,
    sourceUpdatedAt: '2026-03-16',
  },
  {
    name: 'vercel-react-best-practices',
    nameLang: 'en',
    summaryCn: '来自 Vercel 工程团队的 React 和 Next.js 性能优化指南。用于编写、审查或重构 React/Next.js 代码，确保最佳性能模式。',
    description: 'React and Next.js performance optimization guidelines from Vercel Engineering.',
    category: 'development',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Cursor']),
    author: 'vercel-labs',
    stars: 28800,
    sourceUpdatedAt: '2026-04-14',
  },
  {
    name: 'writing-clearly-and-concisely',
    nameLang: 'en',
    summaryCn: '帮助 AI 更清晰简洁地写作。减少冗余词汇和重复表述，使用主动语态，确保每句话都有实质内容。适用于技术文档、邮件、报告等场景。',
    description: 'Helps AI write more clearly and concisely. Reduces redundant words and repetitive phrasing.',
    category: 'content-media',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/writing/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-01-15',
  },
  {
    name: 'mcp-builder',
    nameLang: 'en',
    summaryCn: '构建 MCP（Model Context Protocol）服务器的指南，使 LLM 能够通过设计良好的工具与外部服务交互。涵盖 Python 和 Node/TypeScript 实现。',
    description: 'Guide for creating MCP (Model Context Protocol) servers that enable LLMs to interact with external services.',
    category: 'development',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/mcp-builder/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', 'Cursor']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-20',
  },
  {
    name: 'webapp-testing',
    nameLang: 'en',
    summaryCn: '使用 Playwright 与本地 Web 应用交互和测试的工具包。支持验证前端功能、调试 UI 行为、捕获浏览器截图和查看浏览器日志。',
    description: 'Toolkit for interacting with and testing local web applications using Playwright.',
    category: 'testing-security',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/webapp-testing/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-10',
  },
  {
    name: 'xlsx',
    nameLang: 'en',
    summaryCn: '创建、读取、编辑和分析 Excel 电子表格（.xlsx/.xlsm）。支持公式、格式化、图表、数据分析和多工作表操作。',
    description: 'Create, read, edit, and analyze Excel spreadsheets (.xlsx/.xlsm).',
    category: 'office-productivity',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-01-25',
  },
  {
    name: 'pdf',
    nameLang: 'en',
    summaryCn: '全面的 PDF 处理工具包：提取文本和表格、创建新 PDF、合并/拆分文档、处理表单。适用于文档分析、报告生成等场景。',
    description: 'Comprehensive PDF manipulation toolkit: extract text and tables, create new PDFs, merge/split documents.',
    category: 'office-productivity',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/pdf/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', '通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-01',
  },
  {
    name: 'algorithmic-art',
    nameLang: 'en',
    summaryCn: '使用 p5.js 创建算法艺术。支持生成式视觉、交互式动画、粒子系统和几何图案。适用于创意编程和数据可视化项目。',
    description: 'Creating algorithmic art using p5.js. Supports generative visuals, interactive animations, particle systems.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/algorithmic-art/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-20',
  },
  {
    name: 'slack-gif-creator',
    nameLang: 'en',
    summaryCn: '创建优化的 Slack 动画 GIF。提供大小约束、帧率优化和调色板管理知识，确保 GIF 在 Slack 中完美显示。',
    description: 'Creating optimized animated GIFs for Slack. Provides knowledge of size constraints, frame rate optimization.',
    category: 'content-media',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/slack-gif/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-01-05',
  },
  {
    name: 'theme-factory',
    nameLang: 'en',
    summaryCn: '为幻灯片、文档、报告和网页应用生成专业主题。提供 10+ 预设主题（如"Ocean Depths"、"Sunset Boulevard"），每个主题有精心配色的调色板和字体搭配。',
    description: 'Toolkit for styling artifacts with professional themes. Provides 10 preset themes with well-coordinated color palettes.',
    category: 'design-creative',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/theme-factory/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-04-05',
  },
  {
    name: 'internal-comms',
    nameLang: 'en',
    summaryCn: '撰写各种内部沟通文档：状态报告、领导层更新、项目更新、FAQ、事件报告等。帮助 AI 以合适的语气和结构撰写专业内部通讯。',
    description: 'Writing various internal communications: status reports, leadership updates, project updates, FAQs, incident reports.',
    category: 'business',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/internal-comms/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', '通用']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-02-28',
  },
  {
    name: 'data-analysis',
    nameLang: 'en',
    summaryCn: '使用 Python 进行数据分析：数据清洗、统计分析、可视化和洞察提取。支持 pandas、matplotlib、seaborn 等常用库。',
    description: 'Data analysis using Python: data cleaning, statistical analysis, visualization, and insight extraction.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/anthropics/skills/blob/main/skills/data-analysis/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', 'Cursor']),
    author: 'anthropics',
    stars: 159000,
    sourceUpdatedAt: '2026-03-10',
  },
  {
    name: '单元测试生成器',
    nameLang: 'zh',
    summaryCn: '为给定代码自动生成完整的单元测试用例。支持 Jest、Vitest、Pytest 等主流测试框架，涵盖正常路径、边界条件和异常场景。',
    description: '为给定代码自动生成完整的单元测试用例。支持 Jest、Vitest、Pytest 等主流测试框架。',
    category: 'testing-security',
    sourceUrl: 'https://github.com/codebuddy-ai/skills/blob/main/testing/SKILL.md',
    sourceType: 'community',
    platform: JSON.stringify(['Codex', 'Cursor', '通用']),
    author: 'codebuddy-community',
    stars: 12800,
    sourceUpdatedAt: '2026-06-15',
  },
  {
    name: '项目架构设计',
    nameLang: 'zh',
    summaryCn: '为软件项目提供架构设计方案。包括技术选型建议、目录结构规划、模块划分、数据流设计和部署架构，帮助团队快速启动新项目。',
    description: '为软件项目提供架构设计方案。包括技术选型建议、目录结构规划、模块划分、数据流设计和部署架构。',
    category: 'development',
    sourceUrl: 'https://github.com/codebuddy-ai/skills/blob/main/architecture/SKILL.md',
    sourceType: 'community',
    platform: JSON.stringify(['Claude Code', 'Codex', '通用']),
    author: 'codebuddy-community',
    stars: 12800,
    sourceUpdatedAt: '2026-06-10',
  },
  {
    name: 'daily-standup',
    nameLang: 'en',
    summaryCn: '根据 Git 提交记录自动生成每日站会报告。汇总昨日完成、今日计划和阻塞项，格式化输出适用于 Slack/Teams 的文本。',
    description: 'Automatically generate daily standup reports from Git commit history.',
    category: 'business',
    sourceUrl: 'https://github.com/obra/superpowers/blob/main/skills/daily-standup/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code']),
    author: 'obra',
    stars: 248200,
    sourceUpdatedAt: '2026-06-25',
  },
  {
    name: 'test-driven-development',
    nameLang: 'en',
    summaryCn: '遵循 TDD 红-绿-重构循环：先写失败测试，再写最小实现使其通过，最后重构优化。确保每个功能都有测试覆盖。',
    description: 'Follow the TDD red-green-refactor cycle: write failing tests first, then minimal implementation.',
    category: 'testing-security',
    sourceUrl: 'https://github.com/obra/superpowers/blob/main/skills/tdd/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', 'Cursor']),
    author: 'obra',
    stars: 248200,
    sourceUpdatedAt: '2026-05-30',
  },
  {
    name: 'git-commit-messages',
    nameLang: 'en',
    summaryCn: '按照 Conventional Commits 规范生成清晰的 Git 提交信息。自动分析代码变更并生成 feat/fix/chore 等类型标注的提交信息。',
    description: 'Generate clear Git commit messages following Conventional Commits specification.',
    category: 'development',
    sourceUrl: 'https://github.com/obra/superpowers/blob/main/skills/git-commits/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'obra',
    stars: 248200,
    sourceUpdatedAt: '2026-04-30',
  },
  {
    name: 'seo-optimizer',
    nameLang: 'en',
    summaryCn: '网页 SEO 优化指南：关键词策略、元标签优化、结构化数据、Core Web Vitals 改进和内容优化建议。',
    description: 'Web SEO optimization guide: keyword strategy, meta tag optimization, structured data, Core Web Vitals.',
    category: 'business',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/seo/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-05-15',
  },
  {
    name: 'prompt-engineering',
    nameLang: 'en',
    summaryCn: '优化和改进 AI 提示词的系统方法。涵盖提示结构设计、上下文管理、链式推理、few-shot 示例和输出格式控制。',
    description: 'Systematic approach to optimizing and improving AI prompts.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/prompt-eng/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-05-01',
  },
  {
    name: 'debugging-assistant',
    nameLang: 'en',
    summaryCn: '系统化调试助手：分析错误日志、追踪调用栈、检查变量状态、定位根因并提供修复方案。支持多种编程语言和框架。',
    description: 'Systematic debugging assistant: analyze error logs, trace call stacks, inspect variable states.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/debugging/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['Claude Code', 'Codex', 'Cursor', '通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-06-01',
  },
  {
    name: 'sql-query-optimizer',
    nameLang: 'en',
    summaryCn: '分析和优化 SQL 查询性能。识别慢查询、建议索引优化、重写低效查询，并提供 EXPLAIN 分析解读。',
    description: 'Analyze and optimize SQL query performance. Identify slow queries, suggest index optimizations.',
    category: 'data-ai',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/sql-optimizer/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-04-10',
  },
  {
    name: 'api-documentation',
    nameLang: 'en',
    summaryCn: '为 RESTful API 生成清晰、完整的文档。支持 OpenAPI/Swagger 格式，包含端点描述、请求/响应示例、认证说明和错误码。',
    description: 'Generate clear and complete documentation for RESTful APIs. Supports OpenAPI/Swagger format.',
    category: 'development',
    sourceUrl: 'https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/skills/api-docs/SKILL.md',
    sourceType: 'github',
    platform: JSON.stringify(['通用']),
    author: 'Shubhamsaboo',
    stars: 116700,
    sourceUpdatedAt: '2026-04-15',
  },
];

async function seed() {
  console.log('🌱 开始导入种子数据...');

  let imported = 0;
  let skipped = 0;

  for (const skill of SEED_SKILLS) {
    const existing = await prisma.skill.findFirst({
      where: { sourceUrl: skill.sourceUrl },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.skill.create({
      data: {
        ...skill,
        tags: '[]',
        isNew: 1,
        status: 'published',
        createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
      },
    });
    imported++;
  }

  console.log(`✅ 导入完成：新增 ${imported} 个，跳过 ${skipped} 个（已存在）`);
  const count = await prisma.skill.count();
  console.log(`📊 数据库共有 ${count} 个 Skill`);
}

seed()
  .catch((e) => {
    console.error('❌ 导入失败:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
